# Generated by Django 5.2.9 on 2025-12-25 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_profilet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilet',
            new_name='Profile',
        ),
    ]
